### ISSUE TITLE
Can't connect to self-hosted server using own tls certificate

### ISSUE THREAD

**Issue by victornsc** [ranfdev/Notify#21]
I get this error when I subscribe to a topic on my self-hosted server:

```
0: error trying to connect: invalid peer certificate: UnknownIssuer
```

The server is using a certificate signed by my own CA.

I switched from ```rustls-tls``` to ```rustls-tls-native-roots``` and now everything works fine.

rustls-tls trust roots are baked into the library whereas native-roots gets them from the operating system, which allows us to load our own CA/certificate.

Since a lot of people are self hosting their ntfy server, I think making the change will prevent them from running into the same problem.

**Comment by test123-all** [comment]
Hello :),
I have the exact same error and problem as @victornsc that I want to use a selfsigned CA-Certificate inside of a intranet and your Notify app doesn't use the certificates from the operating system (set with the `/usr/local/share/ca-certificates/` path and the `update-ca-certificates` CLI-tool).

I also tried to build the project with gnome-builder myself but I get a build error that seems to reside in the code base. Since I don't know anything about gnome-builder and not much about Rust, and already got SDK-dependency errors from gnome-builder, that have taken me some time, I will mark this problem as unresolved for now and will hope for an update.

Yours sincerely

**Comment by ranfdev** [comment]
Sorry for the delay. It should be fixed now. I'm now going to make some other changes to the app and then I'll publish a release on flathub

**Comment by ikogan** [comment]
I'm having this issue on the latest release on Flathub. Has this been published in 0.1.6 on flathub? `openssl` on my host claims the certificate is valid but Notify does not.

```
ERROR notify::error: source="GtkButton" error=Failed: remote exception: Failed: error sending request for url (https://redacted/stats/auth): error trying to connect: invalid peer certificate: UnknownIssuer
```

**Comment by ranfdev** [comment]
Yes, 0.1.6 is already on flathub. Strange that you are still having that error.

**Comment by ikogan** [comment]
Is there any way I can help get this debugged? My certificate works with `openssl` on the host as well as Chrome and Firefox with the same user. None of those are flatpaks.
